### ISSUE TITLE
Paste from .py to python-split not working well

### ISSUE THREAD

**Issue by bhanu151** [luk400/vim-jukit#1]
Hi Lukas,

Whenever I try sending code from my .py file (obtained from converting my ipython notebook via jukit) using jukit#SendSelection(), I just see it as "\%paste". The actual line does not get copied. I'm not sure why this is occurring. I'm using neovim. Here are more details.
Neovim version - NVIM v0.7.0-dev
Kitty version - 0.24.4
Clipboard tool - xclip

Please can you help troubleshoot. I'm new to this.
Thanks,
Bhanu

![Screenshot from 2022-03-22 10-53-37](https://user-images.githubusercontent.com/21968419/159415232-2f321497-7220-4d93-a138-0da61a319bce.png)
![Screenshot from 2022-03-22 10-56-30](https://user-images.githubusercontent.com/21968419/159415252-1a6b901f-9058-44e3-8d97-3c152951c2a6.png)
[test.ipynb.txt](https://github.com/luk400/vim-jukit/files/8321494/test.ipynb.txt)

**Comment by luk400** [comment]
Hi, very sorry for the late reply.
I could not reproduce your issue with the same kitty and neovim version, but it seems like the text in the jukit-register (@x) which is sent to the kitty split is not escaped correctly. 
Please post the output of the following function:
```
fun! Escape(text)
python3 << EOF
import vim, json
txt = vim.eval('a:text')
escaped = txt.translate(str.maketrans({"\n": "\\\n", "%": "\%"}))
vim.command("let escaped_text = shellescape({})".format(json.dumps(escaped)))
EOF
    return escaped_text
endfun
echo Escape('%paste\n')
```
Expected output is `'\%paste\n'`

If this is the case, check if `exe '!kitty @ send-text --match title:' . b:jukit_output_title . ' ' . Escape('%paste\n')` sends the `%paste` command correctly to the ipython split.


I will release a major overhaul of the current plugin with lots of new functionality and which doesn't rely on the system clipboard relatively soon (most likely within the next 2-3 weeks), which should be more robust/polished and which most likely gets rid of your issue in case we can't get this sorted out for you.

**Comment by bhanu151** [comment]
Hi Lukas! Thanks for the response. My neovim config is in lua. Is there an equivalent lua script I could test? 
Great to hear that the new functionality doesn't rely on the system clipboard. My issue might most likely be related to that. 
Thanks!

**Comment by bhanu151** [comment]
Thanks! Here's what I see in response to copying the function and using `:@+` in neovim
`'\\%paste\\n'`

**Comment by luk400** [comment]
I implemented a possible workaround in https://github.com/luk400/vim-jukit/commit/c347de92eaeeef255075efb40f83c20084e3f0e7. Please reinstall the plugin and see if this fixed your issue.

**Comment by bhanu151** [comment]
Thanks for the fix. The paste is working fine now.
