### ISSUE TITLE
[Feature Request] Jump to next/previous cell

### ISSUE THREAD

**Issue by igorlfs** [luk400/vim-jukit#24]
Mappings to jump between cells would be pretty useful for navigation!

**Comment by luk400** [comment]
thanks for the suggestion, should be pretty straight forward to implement. I'll get to it in the next few days

**Comment by luk400** [comment]
I have now added the functions `jukit#cells#jump_to_previous_cell()` and `jukit#cells#jump_to_next_cell()` which should do what you want and which I currently mapped to `<leader>K` and `<leader>J` respectively.

Also just fyi, in case you prefer it,  you can change the argument in the send-section mapping (`nnoremap <leader><space> :call jukit#send#section(0)<cr>`) from 0 to 1, which makes it so you automatically jump to the next cell after executing the current cell :)

**Comment by igorlfs** [comment]
> I have now added the functions `jukit#cells#jump_to_previous_cell()` and `jukit#cells#jump_to_next_cell()` which should do what you want and which I currently mapped to `<leader>K` and `<leader>J` respectively.

Thanks!

> Also just fyi, in case you prefer it, you can change the argument in the send-section mapping (nnoremap <leader><space> :call jukit#send#section(0)<cr>) from 0 to 1, which makes it so you automatically jump to the next cell after executing the current cell :)

I've been using this, but I still felt the need for a feature specific to dealing with movement, specially when using notebooks with Markdown.
