### ISSUE TITLE
Is there an option to force the conversion?

### ISSUE THREAD

**Issue by aemonge** [luk400/vim-jukit#31]
Is there an option for: `call jukit#convert#notebook_convert()` or `call jukit#convert#notebook_convert("%")` to set default answer for the next two prompts: **Do you want to overwrite?** And **do you want to open?**

**Comment by luk400** [comment]
Currently not, but I can easily add an option to do so. I'll most likely add it sometime this weekend.

**Comment by luk400** [comment]
You can now configure default options via the variables `g:jukit_convert_open_default` and `g:jukit_convert_overwrite_default` - [see relevant section in readme](https://github.com/luk400/vim-jukit#basic-jukit-options)

**Comment by aemonge** [comment]
Thank you so very much ❤️ , you have made my 🐍 python-dev experience so much better. I'm learning it through Udacity,
and it's heavily based on Jupiter NoteBooks web interface. As a (n)Vim user you can understand the frustration, so I
deeply 🙇 thank you!

**Comment by luk400** [comment]
Thank you, I'm glad you like it! :)
