### ISSUE TITLE
Override mapping

### ISSUE THREAD

**Issue by ls-devs** [luk400/vim-jukit#41]
Hi,
I would like to use my own keys mapping for your plugin.
I can't find any documentation, or solution provided to do this.
The only way for me actually is to modify the plugin mapping directly from the plugin files.

Can you provide a way to change keymaps for your plugin ? 
Thanks

**Comment by luk400** [comment]
Simply specify your mappings for the relevant functions [as shown in the readme](https://github.com/luk400/vim-jukit#functions-and-default-mappings) (before the plugin is loaded) and it should work

**Comment by ls-devs** [comment]
Thanks, I was overriding the mappings after plugin was loaded, so of course it didn't work ! :)
