### ISSUE TITLE
Add instructions on how to install ueberzug

### ISSUE THREAD

**Issue by luk400** [luk400/vim-jukit#44]
Update readme with instructions on how to install ueberzug, since it's not available via pip anymore

**Comment by jyue86** [comment]
Hi, I started using your plugin and really enjoy having it as part of my workflow! I was wondering if there's an update on how to install ueberzug; I've noticed that it's no longer maintained, and there doesn't seem to be other documentation on how to install it.

**Comment by jyue86** [comment]
I went back through the readme and noticed that kitty seems to support functionality similar to ueberzug out of the box, so I started using kitty. Works really well! :)

Still, I did some digging. I can't speak for other distros, but for Ubuntu based distros >= 22.10, they're able to install ueberzug with apt. This is the source I'm referring to: [link](https://launchpad.net/ubuntu/+source/ueberzug).

**Comment by luk400** [comment]
Hi, thank you for reminding me. You can install überzug for python by reverting to an older tag of the no longer maintained ueberzug repo, cloning it and installing it manually via setup.py - I have now added the relevant instructions to the readme

> I went back through the readme and noticed that kitty seems to support functionality similar to ueberzug out of the box

while kitty is used to display plots via matplotlib, uberzug is intended to provide different functionality in this plugin, which is to overlay saved python outputs in the terminal without having to open a separate split window for displaying them
