### ISSUE TITLE
In-terminal matplotlib plots

### ISSUE THREAD

**Issue by FahimAnayet** [luk400/vim-jukit#5]
If it is possible can you please add support for iTerm2?

**Comment by luk400** [comment]
I'm not familiar with iTerm2 at all, so I can't guarantee that it'll work or be implemented anytime soon, but I'll look into it when I have time next week and update you as soon as I know more

**Comment by luk400** [comment]
Not sure if you're interested in this anymore since you closed this issue, but I just wanted to let you know that in-terminal plotting is now implemented (though still experimental) for iTerm2 with tmux (tested using iTerm2 Build 3.4.15 + tmux version 3.2a), see the current readme.
