### ISSUE TITLE
Integration with kitty on Linux

### ISSUE THREAD

**Issue by davidluna-fn** [luk400/vim-jukit#53]
![image](https://user-images.githubusercontent.com/28846713/213947458-724bd06e-c4e9-4c43-b586-89b47bf31af8.png)

Hi, I get this error when I try to make a split after configuring the plugin to work with kitty terminal.

![image](https://user-images.githubusercontent.com/28846713/213947605-fc467103-2047-4212-a8b7-f22de05e162f.png)

**Comment by luk400** [comment]
hi, which version of kitty and which OS are you using? did you configure kitty as specified in the readme?

**Comment by davidluna-fn** [comment]
I've identified the problem, I'm using tmux + kitty so it doesn't work, I deactivated tmux and it worked perfectly.
