### ISSUE TITLE
UsageError: Line magic function `%jukit_run` not found.

### ISSUE THREAD

**Issue by imaphatduc** [luk400/vim-jukit#6]
I faced this error when running code blocks in the split output terminal. (Pressing the default keybinding `<leader>os`)

Here is my system information:
- Linux distro: Arch Linux.
- Terminal: Alacritty.
- Neovim: v0.6.1.
- Python: v3.10.4.
- Arch package `ipython` v8.2.0 installed.

Am I missing something here?

**Comment by luk400** [comment]
This suggests that the ipython custom magics were not loaded, though it works as expected for me with the same python and ipython versions. In your ipython shell (after starting it using `<leader>os`), do you see the plugin path when running `print(sys.path)` (i.e. a string containing `.../vim-jukit/helpers`)?

If so, does the following code execute without error in your shell?
```python
from IPython import get_ipython
shell = get_ipython()
shell.magic("%load_ext jukit_run")
```

**Comment by imaphatduc** [comment]
So I can see that not installing all modules required in the IPython file caused this problem (`matplotlib` and `numpy` in my case). But after installing them, I got this below error message:
```
AssertionError: Must first run `%jukit_init <path/to/file.py>`
```

**Comment by luk400** [comment]
numpy should not be necessary since it's not used by vim-jukit, only matplotlib is required. I've added the possibility to better debug the ipython cmd that's run to start the ipython shell and load the ipython magics. 
Please reinstall the plugin, specify `let g:jukit_debug=1` in your neovim config, then start editing your python file and open the split using `<leader>os`. Do you get any errors in the output split immediately after starting the shell? If not, it should work as expected.

**Comment by imaphatduc** [comment]
I've done all the steps you said, and after starting the shell, it said `UsageError: argument in_style: invalid int value: '-'`, and the `AssertionError` message above is still there. It seems like the error happened when it ran the code you provided.

> ```python
> from IPython import get_ipython
> shell = get_ipython()
> shell.magic("%load_ext jukit_run")
> shell.magic("%jukit_init example-file.py")
> ```

I guessed maybe the `-` symbol in the file name violates the scripts? Because if I change file names from hyphens to underscores, the shell says `UsageError: argument in_style: invalid int value: '_'`

**Comment by luk400** [comment]
This is very strange, the `-` shouldn't throw it off in any way, and it works fine for me with the same specifications as you. The error suggests that the string argument in `__shell.magic(...)` is not parsed correctly when starting the shell. Could you please post a screenshot of the shell with said error messages so I can check what's actually sent to the shell?

**Comment by luk400** [comment]
This is a shot in the dark, but I now replaced occurrences of `shell.magic(...)` with `shell.run_line_magic(<magic>, <param>)`, since `shell.magic(...)` seems to be deprecated. Please reinstall the plugin and check if you still get the same error when starting the output split, and if so, please post a screenshot.

**Comment by imaphatduc** [comment]
The error message is still there.
![2022-04-18-18:09:48-screenshot](https://user-images.githubusercontent.com/51194912/163800166-ccca0cf8-d417-4e88-87d4-cfc1eb6462de.png)
Here it is.

**Comment by imaphatduc** [comment]
Btw, thanks for your work on maintaining this project! It's amazing to see IPython in (Neo)vim, but I'm not sure why it didn't work on my machine.

**Comment by luk400** [comment]
> The error message is still there.
> ![2022-04-18-18:09:48-screenshot](https://user-images.githubusercontent.com/51194912/163800166-ccca0cf8-d417-4e88-87d4-cfc1eb6462de.png)
> Here it is.

Thank you, but could you also post a screenshot of the shell immediately after opening it with `<leader>os` (without executing anything else yourself)?

> Btw, thanks for your work on maintaining this project! It's amazing to see IPython in (Neo)vim, but I'm not sure why it didn't work on my machine.

You're welcome, I have no idea either unfortunately, let's see if we can figure this out.

**Comment by imaphatduc** [comment]
Here you are.

![2022-04-18-19:03:46-screenshot](https://user-images.githubusercontent.com/51194912/163805718-b2ab00c7-019e-434a-8640-c2dd2245969b.png)

**Comment by imaphatduc** [comment]
Ah because of the whitespaces! I should have been aware of them... anw, thank you! I'll definitely check it out as soon as this is fixed.

**Comment by luk400** [comment]
I've implemented a fix, please check if the shell now starts without error after reinstalling the plugin

**Comment by imaphatduc** [comment]
Now it works. Thank you! I'll close this issue now.

**Comment by luk400** [comment]
> Now it works. Thank you! I'll close this issue now.

Glad it's working, thanks again for pointing this out!
