### ISSUE TITLE
Open in new os window

### ISSUE THREAD

**Issue by piotryordanov** [luk400/vim-jukit#65]
Is the open in new os window only applicable for Kitty?
I'm running alacritty in wsl, and the option seems to be ignored!

**Comment by luk400** [comment]
Hello, yes this option is only for kitty, [see the relevant kitty options in the readme](https://github.com/luk400/vim-jukit#kitty)

**Comment by piotryordanov** [comment]
Oki. Thx!

**Comment by piotryordanov** [comment]
@luk400 so this works like a charm in kitty.
However, my `jukit_layout` configs are not respected.
Is it because the newly spawned window is controlled by my DM (in this case, hyprland) ?
