### ISSUE TITLE
[Rich] Empty output when pressing enter

### ISSUE THREAD

**Issue by blob42** [luk400/vim-jukit#66]
When using the Rich extension, I get an empty result when I call jukit send cell. However when I manually jump to the output window and fill in my object then press enter I get the message printed with markup colors using Rich. 

Is there something particular your are doing that would cause this ?

I can manually use `print(...)` without problem it looks like only related to `__repr__`

**Comment by luk400** [comment]
Yeah vim-jukit redirects stdout to capture and save ipython outputs, and rich also redirects IO which seems to cause the issues. I have implemented a (kind of hacky) workaround which is the best I can do for now. Please reinstall the plugin and see if it works for you.

**Comment by blob42** [comment]
Thanks for the quick fix ! It seems working perfectly well now. Also thank you very much for the work you've done with this plugin.
