### ISSUE TITLE
support for open ipynb in vscode

### ISSUE THREAD

**Issue by Aneeqasif** [luk400/vim-jukit#71]
i can open a python file in jupyter notebook with leader np , please add an option or keybind to open the notebook in custom programe majaor ones will be vs code jupyterlab etc

**Comment by luk400** [comment]
Hi, you can now specify `let g:jukit_notebook_viewer = 'code'` somewhere in your vim config (before the plugin is loaded) to e.g. use vs code for opening notebooks.

**Comment by Aneeqasif** [comment]
> Hi, you can now specify `let g:jukit_notebook_viewer = 'code'` somewhere in your vim config (before the plugin is loaded) to e.g. use vs code for opening notebooks.

but there is a issue after pressing np , the python code is converted to ipynb and then jupyter notbook is opened, and user gets prompted 2 times and even then the comand mode is saying to presc ctrl-c to close.

can you please provide an option to toggle on/off these prompts of yes/no

**Comment by luk400** [comment]
Did you reinstall the plugin first? Because I only added this functionality yesterday

**Comment by luk400** [comment]
Regarding the prompts, see the options `g:jukit_convert_open_default` and `g:jukit_convert_overwrite_default` in the readme

**Comment by Aneeqasif** [comment]
thanks sir
