### ISSUE TITLE
support request for octave

### ISSUE THREAD

**Issue by Aneeqasif** [luk400/vim-jukit#72]
please add support for ocatve, it has python like repel and i hope it will be easyily added 
peace :)

**Comment by luk400** [comment]
Hi, this should hopefully already work if you set the following in your vim session:
```vim
let g:jukit_shell_cmd = 'octave'
let g:jukit_comment_mark = '%' " only required if you don't have or don't use the tcomment plugin (i.e. g:jukit_use_tcomment==0)
```

(Note however that features such as output saving or in-terminal plotting are only supported for python)

**Comment by Aneeqasif** [comment]
> 

tsm ill try and get back to u
