### ISSUE TITLE
How to enable a plugin only for ipynb files in vimrc?

### ISSUE THREAD

**Issue by Mingzefei** [luk400/vim-jukit#73]
I'm trying to set up my vimrc so that this wonderful plugin is only loaded or its commands are only executed when opening `*.ipynb` files. 
For example, using `<Enter>` to execute code cells in ipynb files is very convenient, but it causes unnecessary errors and keybinding conflicts when working with other file types. 
Is there a way to control the overall switch of this plugin?

System: WSL2 Ubuntu 20.04 
Software: neovim 0.7.2

**Comment by luk400** [comment]
Hello! Yes, you can set e.g. `let g:jukit_mappings_ext_enabled = ["py", "ipynb"]` in your config (before the plugin is loaded) to only enable the mappings for .py and .ipynb files, see the [relevant section in the readme](https://github.com/luk400/vim-jukit#basic-jukit-options).

**Comment by Mingzefei** [comment]
Thank you! This did the trick. 
I actually missed that in the readme.
