### ISSUE TITLE
jukit also try to run stuff in nvim tree

### ISSUE THREAD

**Issue by Aneeqasif** [luk400/vim-jukit#74]
![image](https://user-images.githubusercontent.com/78728701/229507801-e91489fd-0593-4bb3-b6e8-9f9694938113.png)

when i try to open a file using enter the jukit is trigeres some how

**Comment by luk400** [comment]
See the readme and issue #73 on how to specify filetypes for which to enable the plugin mappings

**Comment by Aneeqasif** [comment]
i dont know after trying it i dont see any difference in the behaviour, i am using nvchad as nvim distribution.
is there any option to disable this plugin on some file types

**Comment by Aneeqasif** [comment]
for example some times it also return folllowing when i press enter to open something in nvimtree
![image](https://user-images.githubusercontent.com/78728701/230107572-c2eca704-b04b-4e20-82cf-df6222bf5833.png)

**Comment by Aneeqasif** [comment]
another issue is with specifying extension for enabling disabling mapping is sometimes i have python scripts that have shbang on them so nvim can get their filetype from shbang, but because it do not have .py the extension , i cannot use vim-jukit
