### ISSUE TITLE
Cell boundary highlighting

### ISSUE THREAD

**Issue by arorashivoy** [luk400/vim-jukit#92]
The documentation is not clear enough on how do i get the green border that is presented in the videos between the cells 

in the documentation it says that you can change the value of the function to this
`let g:jukit_highlight_markers = 'highlight jukit_cellmarker_colors guifg=#1d615a guibg=#1d615a ctermbg=22 ctermfg=22'`

but this doesn't change anything

**Comment by luk400** [comment]
no, you need to specify `highlight jukit_cellmarker_colors guifg=#1d615a guibg=#1d615a ctermbg=22 ctermfg=22` in your vim config, not assign it as a string to the `g:jukit_highlight_markers` variable.
